### ISSUE TITLE
ENHANCE: decouple fastauth from open sourced relayer via config

### ISSUE THREAD

**Issue by anthony-near** [near/pagoda-relayer-rs#18]
```[tasklist]
### Tasks
- [x] Include way to disable use of shared storage pool via config
- [x] Include way to disable fastauth features
- [x] Include way to run without redis
```

**Comment by anthony-near** [comment]
https://github.com/near/pagoda-relayer-rs/pull/24
